### ISSUE TITLE
Plugin fails when .rubocop.yml inherits from another file

### ISSUE THREAD

**Issue by zinkkrysty** [AtomLinter/linter-haml#30]
This happens if the option "Copy rubocop.yml to temporary directory" is active.

`linter-haml error Error: No such file or directory @ rb_sysopen - /var/folders/l1/c7gt0c8x1lsgn49kthq1fmyc0000gn/T/AtomLinter116021-27770-5yvtrn/.rubocop_todo.yml`

Here's how the .rubocop.yml file looks like:

```yaml
---
inherit_from: .rubocop_todo.yml

Style/DotPosition:
  EnforcedStyle: trailing

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/EndAlignment:
  AlignWith: variable

Lint/HandleExceptions:
  Exclude:
    - 'bin/*'

```
